[versions]
agp = "8.5.2"
kotlin = "1.9.24"
coreKtx = "1.13.1"
activityCompose = "1.9.3"
composeBom = "2024.12.01"
navigationCompose = "2.8.5"
lifecycleRuntimeKtx = "2.8.7"

[libraries]
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }

[libraries.androidx-compose-bom]
module = "androidx.compose:compose-bom"
version.ref = "composeBom"

[libraries.androidx-compose-ui]
module = "androidx.compose.ui:ui"

[libraries.androidx-compose-ui-graphics]
module = "androidx.compose.ui:ui-graphics"

[libraries.androidx-compose-ui-tooling-preview]
module = "androidx.compose.ui:ui-tooling-preview"

[libraries.androidx-compose-material3]
module = "androidx.compose.material3:material3"

[libraries.androidx-compose-material-icons-extended]
module = "androidx.compose.material:material-icons-extended"

[libraries.androidx-compose-ui-tooling]
module = "androidx.compose.ui:ui-tooling"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

